name: Next Release

tag: 'v$RESOLVED_VERSION'

categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bug'
  - title: '🧰 Maintenance'
    label: 'chore'

exclude-labels:
  - 'skip-changelog'
  - 'dependencies'

change-template: '- $TITLE (#$NUMBER) @$AUTHOR'

change-title-escapes: '\\<*_&' # You can add # and @ to disable mentions, and add ` to disable other markdown

version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch

template: |
  ## Changes
  $CHANGES

  **Full Changelog**: $PREVIOUS_TAG...$RESOLVED_VERSION

replacers:
  - search: '/<!-- generate-changelog -->[\s\S]+<!-- /generate-changelog -->/g'
    replace: '<!-- generate-changelog -->\n$CHANGES\n<!-- /generate-changelog -->'
